//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StrategyExplorer.rc
//
#define IDD_AboutBox                    100
#define IDS_EDIT                        101
#define IDD_PROPPAGE                    102
#define IDS_TOOL                        103
#define IDM_MENU                        104
#define IDP_SOCKETS_INIT_FAILED         105
#define IDR_MAIN_EDIT                   106
#define IDR_MAIN_TOOL                   107
#define IDR_DOC_TOOL                    108
#define IDM_DOCLIST                     109
#define IDD_BondTerms                   110
#define IDD_StrategyExplorerHiResDlg    111
#define IDR_MAINFRAME                   128
#define IDI_Hedge                       130
#define IDI_StrategyExplorer            130
#define IDI_Nilla_Hedge                 131
#define IDD_InitialPosition             132
#define IDD_InitialStockPosition        133
#define IDD_PositionsDialog             134
#define IDD_BondDefinitionDialog        136
#define IDD_Bond                        137
#define IDD_xStructuredNavigator        138
#define IDD_StrategyExplorer            139
#define IDD_StrategyExplorerNext        140
#define IDD_xHedgeCalculator            141
#define IDD_OptionDefinitionDialog      142
#define IDD_YieldCurveDialog            143
#define IDD_StockDefinitionDialog       144
#define IDD_CurrentStockValue           145
#define IDD_xCurrentStockValue          146
#define IDD_OptionCurrentPosition       147
#define IDD_CurrentOptionValue          148
#define IDD_ClosePositionDialog         149
#define IDD_OptionAnalyzerDialog        150
#define IDD_InitialBondPosition         151
#define IDD_PortfolioNavigatorDialog    152
#define IDR_PositionsPopup              153
#define IDD_xImpliedVolatility          154
#define IDD_xPutCallParityDialog        155
#define IDD_DisplayOptions              156
#define IDD_PositionListDisplayOptions  157
#define IDD_PositionListOptions         158
#define IDD_xPortfolioNavigatorDisplayOptions 159
#define IDD_xDeletePositionsConfirmationDialog 160
#define IDD_BondAnalyzerDialog          161
#define IDD_ConfirmSavePreferencesDialog 162
#define IDB_STATE                       188
#define IDB_FOLDERS                     189
#define IDD_ClosedPositionTranscript    191
#define IDD_PositionsTranscripts        192
#define IDD_PreferencesDialog           193
#define IDD_OptionChainDialog           196
#define IDD_OptionChainDisplayOptions   198
#define IDD_JunkDialog                  200
#define IDD_HedgeAnalyzer               201
#define IDC_5yrYield                    1001
#define IDC_StockSymbol                 1002
#define IDC_StockPrice                  1003
#define IDC_Expiration                  1003
#define IDC_Shares                      1004
#define IDC_CurrentPrice                1005
#define IDC_OptionPrice                 1005
#define IDC_CurrentPriceLabel           1006
#define IDC_SharePriceLabel             1006
#define IDC_UnderlyingPrice             1006
#define IDC_MarketPriceLabel            1006
#define IDC_CompanyLabel                1007
#define IDC_TotalSharesHeld             1007
#define IDC_NextExDivDateLabel          1007
#define IDC_ExDivDateLabel              1007
#define IDC_TotalCostLabel              1008
#define IDC_NextExDivDateResult         1008
#define IDC_ExDivDateResult             1008
#define IDC_TotalCost                   1009
#define IDC_SigmaLabel                  1010
#define IDC_SharesLabel                 1011
#define IDC_BondSymbolLabel             1012
#define IDC_Sigma                       1013
#define IDC_StrikePriceLabel            1013
#define IDC_StockLabel                  1014
#define IDC_ExpiryLabel                 1014
#define IDC_BondLabel                   1015
#define IDC_AnnualReturnLabel           1015
#define IDC_RiskFreeRateLabel           1015
#define IDC_UnderlyingLabel             1015
#define IDC_DaysToLabel                 1015
#define IDC_UnderlyingStockLabel        1015
#define IDC_BuyDateLabel                1016
#define IDC_ValueLabel                  1016
#define IDC_ValueLabelResult            1016
#define IDC_BSValueLabel                1016
#define IDC_EuropeanValueLabel          1016
#define IDC_EuroValueLabel              1016
#define IDC_PutCallLabel                1016
#define IDC_PurchaseDate                1017
#define IDC_EarlyExercisePremiumLabel   1017
#define IDC_Issuer                      1018
#define IDC_PercentLabel                1018
#define IDC_AmericanValueLabel          1018
#define IDC_AmerValueLabel              1018
#define IDC_NumUnits                    1018
#define IDC_CouponAmountLabel           1019
#define IDC_CouponRateLabel             1019
#define IDC_PurchaseDateOverview        1019
#define IDC_CurrentValueResult          1020
#define IDC_NumUnitsOverview            1020
#define IDC_ProfitLossResult            1021
#define IDC_CapitalGain                 1021
#define IDC_MaturityDateLabel           1022
#define IDC_TotalSharesHeldResult       1022
#define IDC_UnpaidCouponsResult         1022
#define IDC_Income                      1022
#define IDC_CapitalGainOverview         1022
#define IDC_ImputedYieldLabel           1023
#define IDC_DividendsResult             1023
#define IDC_NextCouponResult            1023
#define IDC_PercentYield                1023
#define IDC_MaturityDate                1024
#define IDC_CouponsResult               1024
#define IDC_TimeValueOfDividends        1024
#define IDC_RiskFreeDividend            1024
#define IDC_Volatility                  1025
#define IDC_Income2                     1025
#define IDC_DatedDate                   1025
#define IDC_IncepDate                   1025
#define IDC_AnnualReturnResult          1026
#define IDC_3moYield                    1027
#define IDC_NetGain                     1027
#define IDC_3moLabel                    1028
#define IDC_NetGain2                    1028
#define IDC_NetGainOverview             1028
#define IDC_InitialPositionBox          1029
#define IDC_CurrentPositionBox          1030
#define IDC_2yrYield                    1031
#define IDC_AnnualReturnBox             1031
#define IDC_ReturnBox                   1031
#define IDC_PurcaseDateTimePicker       1032
#define IDC_CurrentValueBox             1032
#define IDC_MaturityDatePicker          1033
#define IDC_2yrLabel                    1034
#define IDC_6moLabel                    1035
#define IDC_FaceValue                   1036
#define IDC_ParValue                    1036
#define IDC_BondYieldsLabel             1037
#define IDC_FaceValueLabel              1038
#define IDC_ParValueLabel               1038
#define IDC_1yrLabel                    1039
#define IDC_ImputedYieldResult          1040
#define IDC_3yrLabel                    1041
#define IDC_1yrYield                    1042
#define IDC_Bonds                       1043
#define IDC_30yrLabel                   1044
#define IDC_Stocks                      1045
#define IDC_ShortRateValueLabel         1046
#define IDC_ShortRateResult             1046
#define IDC_ExtSpotRateResult           1046
#define IDC_RiskFreeRateResult          1046
#define IDC_CouponsPerYearLabel         1047
#define IDC_ChiSquaredResult            1047
#define IDC_FitSpotRateResult           1047
#define IDC_ValueResult                 1048
#define IDC_BSValueResult               1048
#define IDC_EuroValueResult             1048
#define IDC_BlackScholesResult          1048
#define IDC_15yrLabel                   1049
#define IDC_BondsLabel                  1050
#define IDC_25yrLabel                   1050
#define IDC_AmerValueResult             1050
#define IDC_BondPriceLabel              1051
#define IDC_WhatIfMarketPriceLabel      1051
#define IDC_ImputedMktPriceLabel        1051
#define ID_Terms                        1052
#define IDC_BondTermsBox                1053
#define IDC_TermsBox                    1053
#define IDC_CouponAmount                1054
#define IDC_CouponRate                  1054
#define IDC_DividendsCheck              1055
#define IDC_DayCountingBox              1055
#define IDC_IncludeDividendsCheck       1055
#define IDC_IncludeDividends            1055
#define IDC_CouponsPerYear              1056
#define IDC_TaxesCheck                  1056
#define IDC_IncludeTaxes                1056
#define IDC_IncludeTaxesInReturn        1056
#define IDC_AccountForTaxesInReturn     1056
#define IDC_RadioActualActual           1057
#define IDC_CouponStartDateStatic       1057
#define IDC_Radio30_360                 1058
#define IDC_SavantResourcesLabel        1058
#define IDC_PocketNumerixLabel          1058
#define IDC_CouponEndDateStatic         1058
#define IDC_RadioActual_360             1059
#define IDC_ProductName                 1059
#define IDC_Version                     1060
#define IDC_Author                      1061
#define IDC_CouponPresentValueStatic    1061
#define IDC_PresentValueCouponStatic    1061
#define IDC_Company                     1061
#define IDC_HedgeIcon                   1062
#define IDC_Dedication                  1062
#define IDC_CouponPresentValueResult    1062
#define IDC_PresentValueCouponResult    1062
#define IDC_FolioIcon                   1063
#define IDC_PresentValueParStatic       1063
#define IDC_ExDividendDateBox           1064
#define IDC_DividendsBox                1064
#define IDC_PresentValueParResult       1064
#define IDC_CouponsPerYearList          1065
#define IDC_DividendLabel               1066
#define IDC_BondListBox                 1066
#define IDC_Dividend                    1067
#define IDC_OptionListBox               1067
#define IDC_Q1Dividend                  1067
#define IDC_Q1DividendDatePicker        1068
#define IDC_Q2DividendDatePicker        1069
#define IDC_Q3DividendDatePicker        1070
#define IDC_Q4DividendDatePicker        1071
#define IDC_Q1ExDivDate                 1072
#define IDC_Q1ExDivDateCheck            1072
#define IDC_Q2ExDivDate                 1073
#define IDC_Q2ExDivDateCheck            1073
#define IDC_6moYield                    1074
#define IDC_Q2Dividend                  1074
#define IDC_StockListBox                1075
#define IDC_Q3Dividend                  1075
#define IDC_Q3ExDivDate                 1076
#define IDC_Q3ExDivDateCheck            1076
#define IDC_Q4ExDivDate                 1077
#define IDC_Q4ExDivDateCheck            1077
#define IDC_OptionSymbol                1078
#define IDC_Q4Dividend                  1078
#define IDC_ExpiryDatePicker            1079
#define IDC_StrikePrice                 1080
#define IDC_RiskFreeRate                1081
#define IDC_RiskFreeRateCheck           1082
#define IDC_OrLabel                     1083
#define IDC_DescLabel                   1084
#define IDC_PurchaseDatePicker          1085
#define IDC_PutRadio                    1086
#define IDC_CallRadio                   1087
#define IDC_Desc                        1088
#define IDC_VegaResult                  1089
#define IDC_DeltaRadio                  1090
#define IDC_AnnualizedReturnLabel       1091
#define IDC_GammaRadio                  1091
#define IDC_PositionsBox                1092
#define IDC_VegaRadio                   1092
#define IDC_PayoffChartBox              1093
#define IDC_GammaRadio2                 1093
#define IDC_30yrYield                   1094
#define IDC_PositionsListBox            1095
#define IDC_7yrYield                    1095
#define IDC_DeltaResult                 1096
#define IDC_PurcaseDatePicker           1097
#define IDC_ElasticityResult            1097
#define IDC_TodaysDatePicker            1098
#define IDC_Options                     1099
#define IDC_OptionsLabel                1100
#define IDC_ExerciseValueLabel          1101
#define IDC_ExerciseBoundaryLabel       1101
#define IDC_TodaysDateLabel             1102
#define IDC_RecommendationLabel         1103
#define IDC_OptionTermsBox              1104
#define IDC_OptionDefinitionBox         1104
#define IDC_UnderlyingSymbolLabel       1105
#define IDC_OptionSymbolLabel           1106
#define IDC_PurchaseDateLabel           1107
#define IDC_5yrLabel                    1108
#define IDC_RadioShortRate              1109
#define IDC_RadioComputeIt              1110
#define IDC_FitDataButton               1111
#define ID_TermsButton                  1112
#define IDC_VolatilityLabel             1113
#define IDC_OptionBox                   1114
#define IDC_VolatilityResult            1114
#define IDC_ITMPercentLabel             1114
#define IDC_StockBox                    1115
#define IDC_ImpliedSpotRateLabel        1115
#define IDC_ITMResult                   1115
#define IDC_BondBox                     1116
#define IDC_NeutralityGoalBox           1117
#define IDC_Note                        1117
#define IDC_GreeksBox                   1117
#define IDC_GammaResult                 1118
#define IDC_BondSymbol                  1118
#define IDC_Note2                       1118
#define IDC_NoteOverview                1118
#define IDC_3yrYield                    1119
#define IDC_RhoResult                   1119
#define IDC_InitiallySuppressPositions  1119
#define IDC_pITMResult                  1119
#define IDC_7yrLabel                    1120
#define IDC_StockSymbolLabel            1120
#define IDC_EpsilonResult               1120
#define IDC_RhoDresult                  1120
#define IDC_StockPriceLabel             1121
#define IDC_StatusResult                1121
#define IDC_StockDesc                   1122
#define IDC_PriceLabel                  1122
#define IDC_QtyLabel                    1122
#define IDC_CompanyNameResult           1122
#define IDC_10yrLabel                   1123
#define IDC_OptionStrikeLabel           1123
#define IDC_StockPriceResult            1123
#define IDC_15yrYield                   1124
#define IDC_OptionExpiryDatePicker      1124
#define IDC_25yrYield                   1125
#define IDC_ExerciseValueResult         1125
#define IDC_PstarValueResult            1125
#define IDC_ExerciseBoundaryResult      1125
#define IDC_MaturityLabel               1126
#define IDC_NoteLabel                   1126
#define IDC_DividendsLabel              1126
#define IDC_CurrentValueLabel           1127
#define IDC_ExDividendDateLabel         1127
#define IDC_InceptionLabel              1127
#define IDC_RecommendationResultLabel   1128
#define IDC_RecommendationResult        1128
#define IDC_BondSymbolCombo             1128
#define IDC_TotalSharesHeldLabel        1128
#define IDC_ShortRateLabel              1129
#define IDC_OptionSymbolCombo           1129
#define IDC_TotalOptionsHeldLabel       1129
#define IDC_ExtSpotRateLabel            1129
#define IDC_10yrYield                   1130
#define IDC_StockSymbolCombo            1130
#define IDC_BlackScholesLabel           1130
#define IDC_ImpliedVolatilityLabel      1131
#define IDC_20yrYield                   1131
#define IDC_20yrLabel                   1132
#define IDC_IncludeDividendsInReturn    1132
#define IDC_PricingErrorLabel           1132
#define IDC_DefinitionBox               1133
#define IDC_ChiSquaredLabel             1133
#define IDC_AdditionalRatesLabel        1133
#define IDC_FittedSpotRateLabel         1134
#define IDC_ComparableYieldsLabel       1134
#define IDC_NeedAnotherStockLabel       1135
#define IDC_SpotRateLabel               1135
#define IDC_StockDefinitionBox          1136
#define IDC_TotalOptionsHeldResult      1138
#define IDC_OptionPriceLabel            1139
#define IDC_UnderlyingSymbol            1140
#define IDC_ImpliedVolatilityResult     1140
#define IDC_AssessmentBox               1141
#define IDC_UnderlyingPriceLabel        1142
#define IDC_PricingErrorResult          1142
#define IDC_MarketValueLabel            1143
#define IDC_BlackScholesParametersBox   1143
#define IDC_PriceWithBlackScholes       1144
#define IDC_UseBlackScholes             1144
#define IDC_UseAnalyticalValue          1144
#define IDC_UnpaidCouponsLabel          1144
#define IDC_PartialCouponLiabilityLabel 1144
#define IDC_PartialCouponValueLabel     1144
#define IDC_MarketValueLabel2           1144
#define IDC_BlackScholes                1145
#define IDC_BlackScholesValue           1145
#define IDC_OptionAnalyzer              1145
#define IDC_NextCouponDateLabel         1145
#define IDC_OptionInitialPositionBox    1146
#define IDC_NillaHedgeIcon              1147
#define IDC_DeltaLabel                  1149
#define IDC_GammaLabel                  1150
#define IDC_ThetaLabel                  1151
#define IDC_VegaLabel                   1152
#define IDC_RhoDLabel                   1153
#define IDC_UnderlyingBox               1154
#define IDC_OmegaLabel                  1154
#define IDC_EpsilonLabel                1155
#define IDC_pITMLabel                   1155
#define IDC_HedgeAdvice                 1157
#define IDC_CurrentYieldResult          1158
#define IDC_OptionCurrentValueBox       1159
#define IDC_YieldToMaturityResult       1159
#define IDC_CurrentYieldLabel           1160
#define IDC_RhoRLabel                   1161
#define IDC_YieldToMaturityLabel        1161
#define IDC_ThetaResult                 1162
#define IDC_ProfitLossLabel             1163
#define IDC_RhoRresult                  1163
#define IDC_USTreasuriesBox             1164
#define IDC_PercentSign                 1164
#define IDC_AdditionalMaturities        1165
#define IDC_PercentSign2                1165
#define IDC_TotalBondsHeldResult        1166
#define IDC_PercentSign3                1166
#define IDC_TotalBondsHeldLabel         1167
#define IDC_YrsLabel                    1167
#define IDC_CouponsLabel                1168
#define IDC_YrsLabel2                   1168
#define IDC_ExpiryResult                1170
#define IDC_PutCallResult               1171
#define IDC_StrikePriceResult           1172
#define IDC_NextDividendDateLabel       1175
#define IDC_BondList                    1176
#define IDC_StocksList                  1178
#define IDC_OptionsList                 1179
#define IDC_ExistingPositions           1182
#define IDC_PositionsList               1183
#define IDC_PositionsTree               1184
#define IDC_EDIT1                       1188
#define IDC_PositionsTranscript         1188
#define IDC_CallStrike1                 1189
#define IDC_CallStrike2                 1190
#define IDC_CallStrike3                 1191
#define IDC_CallStrike4                 1192
#define IDC_CallStrike5                 1193
#define IDC_CallStrike6                 1194
#define IDC_CallStrike7                 1195
#define IDC_CallStrikeLabel             1196
#define IDC_CallBidLabel                1197
#define IDC_CallBid1                    1198
#define IDC_CallsBox                    1199
#define IDC_CallBid2                    1200
#define IDC_CallBid3                    1201
#define IDC_CallBid4                    1202
#define IDC_CallBid5                    1203
#define IDC_CallBid6                    1204
#define IDC_CallBid7                    1205
#define IDC_PutsBox                     1206
#define IDC_OptionsBox                  1210
#define IDC_CallBid                     1211
#define IDC_CallPrice                   1211
#define IDC_PutBid                      1212
#define IDC_PutPrice                    1212
#define IDC_Strike                      1213
#define IDC_PutSymbol                   1214
#define IDC_CallSymbol                  1215
#define IDC_ExpiryDate                  1217
#define IDC_PutPriceLabel               1218
#define IDC_CallPriceLabel              1219
#define IDC_ZivneysLabel                1220
#define IDC_ImpliedRiskFreeRateResult   1221
#define IDC_EarlyExerciseLabel          1222
#define IDC_CHECK_EnableCarr            1222
#define IDC_CheckAmericanValue          1222
#define IDC_PutCallEarlyExerciseResult  1223
#define IDC_PositionListDisplayOptions  1223
#define IDC_ImpliedRiskFreeRateLabel    1224
#define IDC_PortfolioDisplayOptions     1224
#define IDC_InitialCost                 1225
#define IDC_ZivneysValidityHint         1225
#define IDC_ZivneysValidityNote         1225
#define IDC_InitialCost2                1226
#define IDC_MarketValue                 1226
#define IDC_CapitalGainLoss             1227
#define IDC_InitialCostOverview         1227
#define IDC_AggDividends                1228
#define IDC_MarketValueOverview         1228
#define IDC_AnnualizedNetGain           1229
#define IDC_ExerciseValue               1230
#define IDC_AggIncome                   1231
#define IDC_AggregateIncome             1231
#define IDC_DividendNote                1232
#define IDC_AggregateIncomeOverview     1232
#define IDC_PutStrikeLabel              1233
#define IDC_Enter                       1233
#define IDC_AnnualizedNetGainOverview   1233
#define IDC_PutStrike1                  1234
#define IDC_CostLabel                   1234
#define IDC_ExerciseValueOverview       1234
#define IDC_PutStrike3                  1235
#define IDC_Delete                      1235
#define IDC_PutStrike2                  1236
#define IDC_Close                       1236
#define IDC_PutStrike4                  1237
#define IDC_Modify                      1237
#define IDC_PutStrike5                  1238
#define IDC_PutStrike6                  1239
#define IDC_DontShowCheck               1239
#define IDC_PutStrike7                  1240
#define IDC_ConfirmDelete               1240
#define IDC_PutBid1                     1241
#define IDC_NoUndo                      1241
#define IDC_Units                       1241
#define IDC_PutBid8                     1242
#define IDC_ConfirmationRequired        1242
#define IDC_PutBid2                     1243
#define IDC_Symbol                      1243
#define IDC_PutBid3                     1244
#define IDC_MarketPrice                 1244
#define IDC_PutBid4                     1245
#define IDC_GlobalsBox                  1245
#define IDC_ChangeInYield               1245
#define IDC_WhatIfYTM                   1245
#define IDC_PutBid5                     1246
#define IDC_CompoundYieldLabel          1246
#define IDC_PutBid6                     1247
#define IDC_CompoundYieldResult         1247
#define IDC_PutBid7                     1248
#define IDC_DurationLabel               1248
#define IDC_MacauleyDurationLabel       1248
#define IDC_EquivalentYieldLabel        1248
#define IDC_DurationResult              1249
#define IDC_MacauleyDurationResult      1249
#define IDC_PutBidLabel                 1250
#define IDC_ModifiedDurationLabel       1250
#define IDC_SymbolLabel                 1250
#define IDC_PutSymbolLabel              1251
#define IDC_ModifiedDurationResult      1251
#define IDC_UnitsLabel                  1251
#define IDC_CallSymbolLabel             1252
#define IDC_ConvexityLabel              1252
#define IDC_Bond                        1252
#define IDC_ConvexityResult             1253
#define IDC_Option                      1253
#define IDC_Stock                       1254
#define IDC_ChangeInYieldLabel          1254
#define IDC_WhatIfYieldLabel            1254
#define IDC_ActivePositions             1255
#define IDC_WhatIfMarketPriceResult     1255
#define IDC_ImputedMktPriceResult       1255
#define IDC_InterestRateSensitivityBox  1256
#define IDC_SoldDateLabel               1258
#define IDC_NetProceedsLabel            1259
#define IDC_NetProceeds                 1260
#define IDC_ClosingDate                 1261
#define IDC_ClosingNoteLabel            1262
#define IDC_ClosingNote                 1263
#define IDC_Warning                     1264
#define IDC_Tree                        1267
#define IDC_StockNameLabel              1268
#define IDC_DateRange                   1269
#define IDC_Preface                     1270
#define IDC_DefinitionsPreface          1270
#define IDC_DefinitionDialogChangeSymbolVerify 1271
#define IDC_AnalyzerDialogCloseVerify   1272
#define IDC_AnalyzerDialogChangeSymbolVerify 1273
#define IDC_DefinitionDialogCloseVerify 1274
#define IDC_Epilogue                    1275
#define IDC_PositionsPreface            1275
#define IDC_TAB1                        1276
#define IDC_PositionsDialogDeletePositionVerify 1276
#define IDC_ConfirmSaveTab              1276
#define IDC_PositionDialogChangeSymbolVerify 1277
#define IDC_PositionListDisplayOptionsBox 1277
#define IDC_PositionsDialogClosePositionVerify 1277
#define IDC_PositionsDialogModifyPositionVerify 1277
#define IDC_PositionDialogCloseVerify   1278
#define IDC_DefinitionUpdateBox         1278
#define IDC_Positions                   1279
#define IDC_DefinitionStatic            1280
#define IDC_OverviewStatic              1281
#define IDC_InitiallySuppressPositionsStatic 1282
#define IDC_YearStatic                  1282
#define IDC_YearList                    1284
#define IDC_SaveTranscript              1285
#define IDC_StrikeLabel                 1290
#define IDC_Option1Strike               1293
#define IDC_Option1DaysToExpiry         1294
#define IDC_Option1YrsToExpiry          1294
#define IDC_Option2DaysToExpiry         1295
#define IDC_Option2YrsToExpiry          1295
#define IDC_Option3DaysToExpiry         1296
#define IDC_Option3YrsToExpiry          1296
#define IDC_EvalDay                     1297
#define IDC_EvalDayLabel                1301
#define IDC_Strategy                    1302
#define IDC_BuySellLabel                1303
#define IDC_BuyOption1                  1305
#define IDC_SellOption1                 1306
#define IDC_AssumptionStatic            1310
#define IDC_Note1                       1311
#define IDC_Save                        1312
#define IDC_ProgressIndicator           1313
#define IDC_Abort                       1314
#define IDC_Stop                        1314
#define IDC_Fetch                       1315
#define IDC_iVPricingErrorLabel         1316
#define IDC_IvPricingErrorResult        1317
#define IDC_4o3o                        1318
#define IDC_OptionChainDisplayOptionsBox 1319
#define IDC_RequireConirmationPreface   1322
#define IDC_Copyright                   1323
#define IDC_Option1Cost                 1324
#define IDC_CouponStartDate             1324
#define IDC_Option1Qty                  1325
#define IDC_CouponEndDate               1325
#define IDC_Option2Qty                  1326
#define IDC_CouponCalculatorBox         1326
#define IDC_Option3Qty                  1327
#define IDC_StockQty                    1328
#define IDC_Option1Exp                  1329
#define IDC_Option4Qty                  1329
#define IDC_Option2Exp                  1330
#define IDC_Option3Exp                  1331
#define IDC_StrategyLabel               1332
#define IDC_Plot                        1333
#define IDC_Option1SymbolLabel          1334
#define IDC_Option1Symbol               1335
#define IDC_Option2Symbol               1336
#define IDC_Option2SymbolLabel          1337
#define IDC_Option2Cost                 1338
#define IDC_Option3Symbol               1338
#define IDC_Option3Cost                 1339
#define IDC_Option3SymbolLabel          1339
#define IDC_EvalDateLabel               1340
#define IDC_Option4Cost                 1340
#define IDC_Option2Strike               1341
#define IDC_Option3Strike               1343
#define IDC_EvalDate                    1343
#define IDC_BuyOption2                  1344
#define IDC_SellOption2                 1345
#define IDC_BuyOption3                  1346
#define IDC_SellOption3                 1347
#define IDC_BuyStock                    1348
#define IDC_SellStock                   1349
#define IDC_Option1Put                  1350
#define IDC_Option1Call                 1351
#define IDC_Option2Put                  1352
#define IDC_Option2Call                 1353
#define IDC_Option3Put                  1354
#define IDC_Option3Call                 1355
#define IDC_StockPriceUpdatesBox        1356
#define IDC_BuyOption4                  1356
#define IDC_OptionChainStockPriceVerify 1357
#define IDC_OptionChainStockPriceUpdateVerify 1357
#define IDC_SellOption4                 1357
#define IDC_Option4Put                  1358
#define IDC_Option4Call                 1359
#define IDC_Option3Strike2              1360
#define IDC_Option4Strike               1360
#define IDS_CAP_NEW                     32773
#define IDR_NEW_STOCK                   32774
#define IDR_MAIN_NEW                    32775
#define IDR_NEW_BOND                    32776
#define IDR_NEW_OPTION                  32777
#define IDR_NEW_HEDGE                   32778
#define ID_NEW_BOND                     32780
#define ID_NEW_OPTION                   32781
#define ID_NEW_HEDGE                    32782
#define IDS_CAP_STOCK                   32787
#define IDS_CAP_NEW_EDIT                32791
#define ID_TOOLS_EVALUATE_POSITION      32794
#define ID_NEW_STOCK_POSITION           32795
#define ID_CREATE_STOCK_POSITION        32795
#define ID_NEW_STOCK_DEFINITION         32796
#define ID_OPTION_DEFINITION            32797
#define ID_DEFINE_OPTION                32797
#define ID_NEW_OPTION_POSITION          32798
#define ID_CREATE_OPTION_POSITION       32798
#define ID_STOCK_DEFINITION             32799
#define ID_DEFINE_STOCK                 32799
#define ID_TOOLS_EVALUATE_OPTION_POSITION 32800
#define ID_TOOLS_EVALUATE_STOCK_POSITION 32801
#define ID_TOOLS_EVALUATE_OPTION_POSITIONS 32802
#define ID_EVALUATE_OPTION_POSITIONS    32802
#define ID_TOOLS_EVALUATE_STOCK_POSITIONS 32803
#define ID_EVALUATE_STOCK_POSITIONS     32803
#define ID_TOOLS_ANALYZE_OPTION         32804
#define ID_TOOLS_OPTION_ANALYZER        32804
#define ID_TOOLS_COMPUTE_SHORT_RATE     32805
#define ID_TOOLS_SPOT_RATE_ESTIMATOR    32805
#define ID_BOND_DEFINITION              32806
#define ID_DEFINE_BOND                  32806
#define ID_NEW_BOND_POSITION            32807
#define ID_CREATE_BOND_POSITION         32807
#define ID_TOOLS_EVALUATE_BOND_POSITIONS 32808
#define ID_EVALUATE_BOND_POSITIONS      32808
#define IDS_CAP_POSITIONS               32811
#define ID_HEDGE_DEFINITION             32813
#define ID_CREATE                       32814
#define IDS_CAP_CREATE                  32815
#define IDS_ANALYZE                     32816
#define IDR_MAIN_ANALYZE                32817
#define IDS_EVALUATE                    32818
#define IDS_TOOLS                       32820
#define IDR_MAIN_TOOLS                  32821
#define ID_EVALUATE                     32822
#define IDS_CAP_EVALUATE                32824
#define ID_TOOLS_RISKFREEHEDGE          32825
#define ID_TOOLS_RISK_FREE_HEDGE        32826
#define ID_EVALUATE_HEDGE               32827
#define ID_CREATE_HEDGE                 32828
#define ID_TOOLS_HEDGEPOSITIONS         32829
#define ID_TOOLS_HEDGE_CALCULATOR       32830
#define ID_EDIT                         32835
#define IDS_CAP_EDIT                    32837
#define ID_EDIT_DELETE                  32838
#define ID_POSITIONSPOPUP               32840
#define IDS_CAP_POSITIONSPOPUP          32842
#define ID_POSITIONSPOPUP_EDIT          32843
#define ID_POSITIONSPOPUP_DELETE        32844
#define ID_POSITIONS_POPUP_DELETE       32844
#define IDS_CAP_MENUITEM32845           32846
#define ID__EDIT                        32847
#define ID__DELETE                      32848
#define ID_MENUITEM32849                32849
#define ID__MODIFY                      32851
#define ID_DEFINE_STOCK_PUT_CALL_PARITY 32857
#define ID_EVALUATE_PORTFOLIO           32858
#define ID_TOOLS_PORTFOLIOOVERVIEW      32859
#define ID_EVALUATE_BONDPOSITIONS       32862
#define ID_TOOLS_PORTFOLIO_OVERVIEW     32864
#define ID_TOOLS_PORTFOLIO_NAVIGATOR    32864
#define ID_TOOLS_DISPLAYPREFERENCES     32865
#define ID_CREATE_DISPLAY_PREFERENCES   32866
#define ID_TOOLS_DISPLAY_PREFERENCES    32867
#define ID_EDIT_EDIT                    32871
#define IDS_CAP_MENUITEM32872           32873
#define IDS_CAP_DELETEANDMODIFY         32877
#define ID_DELETEONLY_MODIFY            32878
#define ID_POSITIONS_POPUP_MODIFY       32879
#define ID_POSITIONS_POPUP              32880
#define IDS_CAP_MENUITEM32881           32882
#define IDR_PositionsPopupDelete        32883
#define IDS_CAP_DELETE                  32885
#define ID_DELETE_MODIFY                32886
#define IDR_POSITIONS_POPUP             32888
#define ID_CREATE_POSITION              32889
#define ID_EDIT_MODIFY                  32893
#define IDS_CAP_HELP                    32896
#define ID_FILE                         32897
#define IDS_CAP_FILE                    32899
#define ID_TOOLS_BOND_ANALYZER          32900
#define ID_EDIT_CLOSE                   32901
#define ID_DEFINE_CONFIRM_SAVE_OPTIONS  32902
#define ID_TOOLS_VIEW_CLOSED_POSITIONS  32903
#define ID_TOOLS_VIEW_POSITION_TRANSCRIPT 32903
#define ID_TOOLS_STRATEGY_EXPLORER      32904
#define ID_TOOLS_OPTION_CHAIN_RETRIEVER 32905
#define IDR_EDIT                        32908
#define ID_FILE_CLOSEDB                 32912
#define ID_FILE_OPENDB                  32913
#define ID_FILE_OPEN_DATABASE           32914
#define ID_FILE_CLOSE_DATABASE          32915
#define ID_TOOLS_HEDGE_ANALYZER         32916
#define IDS_NEW                         65000
#define IDS_FILE                        65001
#define IDS_MHELP                       65002
#define IDS_SAVE                        65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006
#define IDS_DateFormat                  65007
#define IDS_DBSubDir                    65008
#define IDS_AppName                     65009
#define IDS_DatabaseDirectory           65010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        206
#define _APS_NEXT_COMMAND_VALUE         32917
#define _APS_NEXT_CONTROL_VALUE         1351
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
