//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PNMX_Installer.rc
//
#define IDFETCH                         3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PNMX_INSTALLER_DIALOG       102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDI_BONDMANAGER                 134
#define IDI_MFC                         135
#define IDI_YIELDCURVEFITTER            136
#define IDI_STRATEGYEXPLORER            137
#define IDI_NILLAHEDGE                  138
#define IDI_STOCKMANAGER                139
#define IDD_LICENSE                     140
#define IDC_InvoiceNumber               1000
#define IDC_InvoiceNumberLabel          1001
#define IDC_FirstName                   1002
#define IDC_FirstNameLabel              1003
#define IDC_InvoiceDate                 1004
#define IDC_Title                       1005
#define IDC_LastNameLabel               1006
#define IDC_LastName                    1007
#define IDC_EmailAddress                1008
#define IDC_EmailAddressLabel           1009
#define IDC_InvoiceDateLabel            1010
#define IDC_DeviceIdLabel               1011
#define IDC_DeviceIdResult              1012
#define IDC_StatusLabel                 1013
#define IDC_StatusResult                1014
#define IDC_OsVersionLabel              1015
#define IDC_OsVersionResult             1016
#define IDC_ICON_PLACEHOLDER            1017
#define IDC_YCF_Label                   1017
#define IDC_BuildResult                 1018
#define IDC_SX_Label                    1018
#define IDC_Device_Connected            1019
#define IDC_BILL_OF_MATERIALS_FOUND     1020
#define IDC_BuildLabel                  1021
#define IDC_BondManager                 1021
#define IDC_SM_Label                    1022
#define IDC_PlatformIDLabel             1023
#define IDC_PlatformIDResult            1024
#define IDC_UUIDLabel                   1025
#define IDC_UUIDResult                  1026
#define IDC_MemoryRequiredLabel         1027
#define IDC_MemoryRequiredResult        1028
#define IDC_MemoryAvailLabel            1029
#define IDC_MemoryAvailResult           1030
#define IDC_Device_Connected_Label      1031
#define IDC_DownloadStatusLabel         1032
#define IDC_Subscriptions_Activated     1033
#define IDC_DownloadStatusResult        1034
#define IDC_NillaHedge                  1035
#define IDC_BILL_OF_MATERIALS_FOUND_LABEL 1036
#define IDC_UploadStatusLabel           1037
#define IDC_UploadStatusResult          1038
#define IDC_Subscriptions_Activated_Label 1039
#define IDC_Install_Complete_Label      1040
#define IDC_Binaries_Installed_Label    1040
#define IDC_StrategyExplorer            1041
#define IDC_YieldCurveFitter            1042
#define IDC_ProductsToInstall           1043
#define IDC_Progress                    1044
#define IDC_TBillRates                  1045
#define IDC_OptionChains                1046
#define IDC_InstallStatusLabel          1047
#define IDC_InstallStatusResult         1048
#define IDC_NH_Label                    1049
#define IDC_BM_Label                    1050
#define IDC_MFC_Label                   1051
#define IDI_APP_IMAGE                   1052
#define IDC_MFC_Downloaded              1053
#define IDC_BM_Downloaded               1054
#define IDC_NH_Downloaded               1055
#define IDC_SX_Downloaded               1056
#define IDC_YCF_Downloaded              1057
#define IDC_MFC_Uploaded                1058
#define IDC_BM_Uploaded                 1059
#define IDC_NH_Uploaded                 1060
#define IDC_SX_Uploaded                 1061
#define IDC_YCF_Uploaded                1062
#define IDC_MFC_Installed               1063
#define IDC_BM_Installed                1064
#define IDC_NH_Installed                1065
#define IDC_SX_Installed                1066
#define IDC_YCF_Installed               1067
#define IDC_Ppc_Label                   1068
#define IDC_Ppc_Downloaded              1069
#define IDC_Ppc_Uploaded                1070
#define IDC_Ppc_Installed               1071
#define IDC_Installed_Label             1072
#define IDC_Downloaded_Label            1073
#define IDC_Uploaded_Label              1074
#define IDC_OCR_Downloaded              1075
#define IDC_OC_Label                    1076
#define IDC_TBR_Downloaded              1077
#define IDC_TBR_Label                   1078
#define IDC_Binaries_Installed          1079
#define IDC_Licenses_Installed          1080
#define IDC_OCR_Installed               1081
#define IDC_RICHEDIT21                  1081
#define IDC_TBR_Installed               1082
#define IDC_EDIT1                       1082
#define IDC_Licenses_Installed_Label    1083
#define IDC_Licensed_Label              1084
#define IDC_BM_Licensed                 1085
#define IDC_NH_Licensed                 1086
#define IDC_SX_Licensed                 1087
#define IDC_YCF_Licensed                1088
#define IDC_StockManager                1089
#define IDC_SM_Downloaded               1090
#define IDC_SM_Uploaded                 1091
#define IDC_SM_Installed                1092
#define IDC_SM_Licensed                 1093
#define IDC_CovarAcct                   1094
#define IDC_VAR_Downloaded              1095
#define IDC_CA_Label                    1096
#define IDC_VAR_Installed               1097
#define IDC_MemoryBox                   1098

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
